### ISSUE TITLE
Licensing information

### ISSUE THREAD

**Issue by nilsschmidthamburg** [vpikulik/hunspell_de_compounds#1]
Hi @vpikulik, 

thank you for the great work. This is exactly what I was looking for. I was wondering which Licence applys to your work. Would you mind adding some licensing information?

Thanks and best regards
Nils

**Comment by vpikulik** [comment]
Hi. I'm happy to know that the dictionary is useful. I have no idea wich license can be used here, but "do what you want" is ok from my side. If can suggest some, I will add or you can create a PR.
Thanks!

**Comment by nilsschmidthamburg** [comment]
Hi Vitali, thanks for the quick reply. "Do What You Want" would go closest with MIT Licence. I have created a PR with a template for a licence file (based on githubs templates). If you are happy to provide your work under that licence, feel free to merge the PR. 
Thanks and keep up the good work :-)
